ARG HYRAX_IMAGE_VERSION=hyrax-v5.2.0
FROM ghcr.io/samvera/hyrax/hyrax-base:$HYRAX_IMAGE_VERSION AS hyku-web

USER root
RUN git config --system --add safe.directory \*
ENV PATH="/app/samvera/bin:${PATH}"

USER app
ENV LD_PRELOAD=/usr/lib/libjemalloc.so.2
ENV MALLOC_CONF='dirty_decay_ms:1000,narenas:2,background_thread:true'

ENV TESSDATA_PREFIX=/app/samvera/tessdata
# Fetch from raw.githubusercontent.com (CDN-backed) rather than the github.com
# blob/...?raw=true redirect, which GitHub now rate-limits (HTTP 429) for
# unauthenticated CI fetches and was failing the build.
ADD https://raw.githubusercontent.com/tesseract-ocr/tessdata_best/main/eng.traineddata /app/samvera/tessdata/eng_best.traineddata

############### KNAPSACK SPECIFIC CODE ###################
# This means bundler inject looks at /app/samvera/.bundler.d for overrides
ENV HOME=/app/samvera
# This is specifically NOT $APP_PATH but the parent directory
COPY --chown=1001:101 . /app/samvera
ENV BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
ENV BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
RUN bundle install --jobs "$(nproc)"
############## END KNAPSACK SPECIFIC CODE ################

RUN RAILS_ENV=production SECRET_KEY_BASE=$(bin/rails secret) DB_ADAPTER=nulldb DB_URL='postgresql://fake' bundle exec rails assets:precompile && yarn install
CMD ./bin/web

FROM hyku-web AS hyku-worker
CMD ./bin/worker

# Use a Solr version with patched Log4j to address CVE-2021-44228
FROM solr:8.11.2 AS hyku-solr
ENV SOLR_USER="solr" \
    SOLR_GROUP="solr"
USER root
COPY --chown=solr:solr solr/security.json /var/solr/data/security.json
USER $SOLR_USER

FROM ghcr.io/notch8/scripts/bitnamilegacy-nginx:1.21.6-debian-11-r21 AS hyku-nginx

# Bake this exact commit's compiled assets/vendored pdf.js into the nginx
# image itself, so nginx and Rails always agree on what a deploy's asset URLs
# resolve to - no shared volume, no deploy-time copy step, no accumulation to
# prune (old versions just age out of the image registry like any other tag).
# Tenant/site branding is NOT baked in here - it's user-uploaded at runtime,
# so it stays on the shared EFS volume (see nginx.extraVolumeMounts in
# ops/*-deploy.tmpl.yaml) instead.
COPY --from=hyku-web /app/samvera/hyrax-webapp/public/assets /app/samvera/hyrax-webapp/public/assets
COPY --from=hyku-web /app/samvera/hyrax-webapp/public/pdf.js /app/samvera/hyrax-webapp/public/pdf.js
COPY --from=hyku-web /app/samvera/hyrax-webapp/public/uv /app/samvera/hyrax-webapp/public/uv

# clover/ramp are NOT under hyrax-webapp/public like the above - they were
# generated by `rails generate hyrax:iiif_viewer {clover,ramp}` straight into
# this knapsack's OWN public/ dir (lib/hyku_knapsack/engine.rb serves that
# directory itself, via its own ActionDispatch::Static, since "Rails only
# serves hyrax-webapp/public"). Source and destination differ here on
# purpose: nginx's root is hyrax-webapp/public, so that's where these need to
# land for it to find them.
COPY --from=hyku-web /app/samvera/public/clover /app/samvera/hyrax-webapp/public/clover
COPY --from=hyku-web /app/samvera/public/ramp /app/samvera/hyrax-webapp/public/ramp
