terms:
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#event
    term: Event
  - id: http://publications.europa.eu/resource/authority/public-event-type/COMPETITION_AWARD_CEREMONY
    term: Award Ceremony
  - id: https://schema.org/ChildrensEvent
    term: Childrens Event
  - id: http://publications.europa.eu/resource/authority/public-event-type/CONFERENCE_SUMMIT
    term: Conference
  - id: https://schema.org/ComedyEvent
    term: Comedy Event
  - id: https://schema.org/DanceEvent
    term: Dance Event
  - id: https://github.com/research-technologies/prvoices_schema/wiki/DesignCharrette
    term: Design Charrette
  - id: https://schema.org/ExhibitionEvent
    term: Exhibition
    file_suffixes: [pdf, jpg, jpeg, png]
  - id: https://schema.org/Festival
    term: Festival
  - id: https://schema.org/FoodEvent
    term: Food Event
  - id: https://schema.org/Hackathon
    term: Hackathon
  - id: http://vocab.getty.edu/page/aat/300026673
    term: Lecture
  - id: https://schema.org/LiteraryEvent
    term: Literary Event
  - id: live_performance
    term: Live performance
  - id: https://schema.org/MusicEvent
    term: Music Event
  - id: http://vocab.getty.edu/page/aat/300075520
    term: Residency
    file_suffixes: [pdf, docx, doc]
  - id: https://schema.org/ScreeningEvent
    term: Screening
    file_suffixes: [pdf, mp4, mov]
  - id: https://schema.org/SocialEvent
    term: Social Event
  - id: https://schema.org/SportsEvent
    term: Sports Event
  - id: http://vocab.getty.edu/page/aat/300054792
    term: Symposia
  - id: https://schema.org/TheaterEvent
    term: Theatre Event
  - id: https://schema.org/VisualArtsEvent
    term: VisualArtsEvent
  - id: http://publications.europa.eu/resource/authority/public-event-type/TRAINING_WORKSHOP
    term: Workshop
