terms:
  - id: https://vocabularies.coar-repositories.org/resource_types/c_1162/
    term: Annotation
  - id: https://vocabularies.coar-repositories.org/resource_types/c_86bc/
    term: Bibliography
  - id: https://vocabularies.coar-repositories.org/resource_types/c_6947/
    term: Blog post
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#book
    term: Book
    file_suffixes: [pdf, epub, docx, doc]
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#bookchapter
    term: BookChapter
  - id: https://vocabularies.coar-repositories.org/resource_types/c_3248/
    term: Book part
  - id: https://vocabularies.coar-repositories.org/resource_types/c_ba08/
    term: Book review
  - id: https://vocabularies.coar-repositories.org/resource_types/c_7877/
    term: Clinical study
  - id: https://vocabularies.coar-repositories.org/resource_types/D97F-VB57/
    term: Commentary
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#conferencepaper
    term: Conference Paper
    file_suffixes: [pdf, docx, doc, pptx]
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#conferenceproceeding
    term: Conference Proceeding
  - id: https://vocabularies.coar-repositories.org/resource_types/c_c94f/
    term: Conference output
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18cp/
    term: Conference paper not in proceedings
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18co/
    term: Conference poster not in proceedings
  - id: https://vocabularies.coar-repositories.org/resource_types/R60J-J5BD/
    term: Conference presentation
  - id: https://vocabularies.coar-repositories.org/resource_types/c_6670/
    term: Conference poster
  - id: https://vocabularies.coar-repositories.org/resource_types/c_7acd/
    term: Corrigendum
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#datapaper
    term: Data Paper
  - id: https://vocabularies.coar-repositories.org/resource_types/c_ab20/
    term: Data management plan
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#dissertation
    term: Dissertation
  - id: https://vocabularies.coar-repositories.org/resource_types/c_b239/
    term: Editorial
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#journal
    term: Journal
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#journalarticle
    term: Journal Article
    file_suffixes: [pdf, docx, doc]
  - id: https://vocabularies.coar-repositories.org/resource_types/c_545b/
    term: Letter to the editor
  - id: https://vocabularies.coar-repositories.org/resource_types/c_8544/
    term: Lecture
  - id: https://vocabularies.coar-repositories.org/resource_types/c_0857/
    term: Letter
  - id: https://vocabularies.coar-repositories.org/resource_types/c_2cd9/
    term: Magazine
  - id: https://vocabularies.coar-repositories.org/resource_types/c_0040/
    term: Manuscript
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18wz/
    term: Memorandum
  - id: http://vocab.getty.edu/page/aat/300054676
    term: Methodology
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18cw/
    term: Musical notation
  - id: https://vocabularies.coar-repositories.org/resource_types/c_2fe3/
    term: Newspaper
  - id: https://vocabularies.coar-repositories.org/resource_types/c_998f/
    term: Newspaper article
  - id: https://vocabularies.coar-repositories.org/resource_types/QX5C-AR31/
    term: Other periodical
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#outputmanagementplan
    term: Output Management Plan
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#peerreview
    term: Peer Review
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#preprint
    term: Pre-Print
  - id: https://vocabularies.coar-repositories.org/resource_types/c_186u/
    term: Policy report
  - id: http://vocab.getty.edu/page/aat/300027240
    term: Programme
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18op/
    term: Project deliverable
  - id: https://vocabularies.coar-repositories.org/resource_types/YZ1N-ZFT9/
    term: Research protocol
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18ws/
    term: Research report
  - id: https://vocabularies.coar-repositories.org/resource_types/c_18gh/
    term: Technical report
  - id: https://vocabularies.coar-repositories.org/resource_types/c_71bd/
    term: Technical documentation
  - id: https://vocabularies.coar-repositories.org/resource_types/c_46ec/
    term: Thesis
    file_suffixes: [pdf, docx, doc]
  - id: https://vocabularies.coar-repositories.org/resource_types/c_7a1f/
    term: Bachelor thesis
  - id: https://vocabularies.coar-repositories.org/resource_types/c_db06/
    term: Doctoral thesis
  - id: https://vocabularies.coar-repositories.org/resource_types/c_bdcc/
    term: Master thesis
  - id: https://vocabularies.coar-repositories.org/resource_types/H6QP-SC1X/
    term: Trademark
  - id: https://vocabularies.coar-repositories.org/resource_types/6NC7-GK9S/
    term: Transcription
  - id: https://vocabularies.coar-repositories.org/resource_types/c_baaf/
    term: Research proposal
  - id: https://vocabularies.coar-repositories.org/resource_types/c_efa0/
    term: Review
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#report
    term: Report
    file_suffixes: [pdf, docx, doc]
  - id: https://vocabularies.coar-repositories.org/resource_types/c_2df8fbb1/
    term: Research article
  - id: https://vocabularies.coar-repositories.org/resource_types/c_dcae04bc/
    term: Review article
  - id: https://vocabularies.coar-repositories.org/resource_types/c_7bab/
    term: Software paper
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#studyregistration
    term: Study Registration
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#text
    term: Text
  - id: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/#workflow
    term: Workflow
  - id: https://vocabularies.coar-repositories.org/resource_types/c_8042/
    term: Working paper
